import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/context/provider";
import { Toaster } from "react-hot-toast";
import HeaderAndFooterWrapper from "@/wrapper/HeaderAndFooterWrapper";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <NextTopLoader />
          <HeaderAndFooterWrapper>
            <Toaster />
            {children}
          </HeaderAndFooterWrapper>
        </body>
      </html>
    </Provider>
  );
}
